/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SaudeRouteImport } from './routes/saude'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated.painel'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as EditarTokenRouteImport } from './routes/editar.$token'
import { Route as LegalPoliticaDePrivacidadeRouteImport } from './routes/legal.politica-de-privacidade'
import { Route as LegalTermosDeUsoRouteImport } from './routes/legal.termos-de-uso'
import { Route as AuthenticatedFormulariosIdRouteImport } from './routes/_authenticated.formularios.$id'
import { Route as AuthenticatedFormulariosIdRespostasRouteImport } from './routes/_authenticated.formularios.$id_.respostas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SaudeRoute = SaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarTokenRoute = EditarTokenRouteImport.update({
  id: '/editar/$token',
  path: '/editar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPoliticaDePrivacidadeRoute =
  LegalPoliticaDePrivacidadeRouteImport.update({
    id: '/legal/politica-de-privacidade',
    path: '/legal/politica-de-privacidade',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalTermosDeUsoRoute = LegalTermosDeUsoRouteImport.update({
  id: '/legal/termos-de-uso',
  path: '/legal/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFormulariosIdRoute =
  AuthenticatedFormulariosIdRouteImport.update({
    id: '/formularios/$id',
    path: '/formularios/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormulariosIdRespostasRoute =
  AuthenticatedFormulariosIdRespostasRouteImport.update({
    id: '/formularios/$id_/respostas',
    path: '/formularios/$id/respostas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/saude': typeof SaudeRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/c/$token': typeof CTokenRoute
  '/editar/$token': typeof EditarTokenRoute
  '/legal/politica-de-privacidade': typeof LegalPoliticaDePrivacidadeRoute
  '/legal/termos-de-uso': typeof LegalTermosDeUsoRoute
  '/formularios/$id': typeof AuthenticatedFormulariosIdRoute
  '/formularios/$id/respostas': typeof AuthenticatedFormulariosIdRespostasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/saude': typeof SaudeRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/c/$token': typeof CTokenRoute
  '/editar/$token': typeof EditarTokenRoute
  '/legal/politica-de-privacidade': typeof LegalPoliticaDePrivacidadeRoute
  '/legal/termos-de-uso': typeof LegalTermosDeUsoRoute
  '/formularios/$id': typeof AuthenticatedFormulariosIdRoute
  '/formularios/$id/respostas': typeof AuthenticatedFormulariosIdRespostasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/saude': typeof SaudeRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/c/$token': typeof CTokenRoute
  '/editar/$token': typeof EditarTokenRoute
  '/legal/politica-de-privacidade': typeof LegalPoliticaDePrivacidadeRoute
  '/legal/termos-de-uso': typeof LegalTermosDeUsoRoute
  '/_authenticated/formularios/$id': typeof AuthenticatedFormulariosIdRoute
  '/_authenticated/formularios/$id_/respostas': typeof AuthenticatedFormulariosIdRespostasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/saude'
    | '/painel'
    | '/c/$token'
    | '/editar/$token'
    | '/legal/politica-de-privacidade'
    | '/legal/termos-de-uso'
    | '/formularios/$id'
    | '/formularios/$id/respostas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/auth'
    | '/saude'
    | '/painel'
    | '/c/$token'
    | '/editar/$token'
    | '/legal/politica-de-privacidade'
    | '/legal/termos-de-uso'
    | '/formularios/$id'
    | '/formularios/$id/respostas'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_authenticated'
    | '/auth'
    | '/saude'
    | '/_authenticated/painel'
    | '/c/$token'
    | '/editar/$token'
    | '/legal/politica-de-privacidade'
    | '/legal/termos-de-uso'
    | '/_authenticated/formularios/$id'
    | '/_authenticated/formularios/$id_/respostas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SaudeRoute: typeof SaudeRoute
  CTokenRoute: typeof CTokenRoute
  EditarTokenRoute: typeof EditarTokenRoute
  LegalPoliticaDePrivacidadeRoute: typeof LegalPoliticaDePrivacidadeRoute
  LegalTermosDeUsoRoute: typeof LegalTermosDeUsoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saude': {
      id: '/saude'
      path: '/saude'
      fullPath: '/saude'
      preLoaderRoute: typeof SaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editar/$token': {
      id: '/editar/$token'
      path: '/editar/$token'
      fullPath: '/editar/$token'
      preLoaderRoute: typeof EditarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/politica-de-privacidade': {
      id: '/legal/politica-de-privacidade'
      path: '/legal/politica-de-privacidade'
      fullPath: '/legal/politica-de-privacidade'
      preLoaderRoute: typeof LegalPoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/termos-de-uso': {
      id: '/legal/termos-de-uso'
      path: '/legal/termos-de-uso'
      fullPath: '/legal/termos-de-uso'
      preLoaderRoute: typeof LegalTermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/formularios/$id': {
      id: '/_authenticated/formularios/$id'
      path: '/formularios/$id'
      fullPath: '/formularios/$id'
      preLoaderRoute: typeof AuthenticatedFormulariosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formularios/$id_/respostas': {
      id: '/_authenticated/formularios/$id_/respostas'
      path: '/formularios/$id/respostas'
      fullPath: '/formularios/$id/respostas'
      preLoaderRoute: typeof AuthenticatedFormulariosIdRespostasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedFormulariosIdRoute: typeof AuthenticatedFormulariosIdRoute
  AuthenticatedFormulariosIdRespostasRoute: typeof AuthenticatedFormulariosIdRespostasRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedFormulariosIdRoute: AuthenticatedFormulariosIdRoute,
  AuthenticatedFormulariosIdRespostasRoute:
    AuthenticatedFormulariosIdRespostasRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SaudeRoute: SaudeRoute,
  CTokenRoute: CTokenRoute,
  EditarTokenRoute: EditarTokenRoute,
  LegalPoliticaDePrivacidadeRoute: LegalPoliticaDePrivacidadeRoute,
  LegalTermosDeUsoRoute: LegalTermosDeUsoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
